### ISSUE TITLE
Streaming reads: offsets are not loaded from checkpoint when restarting a stream after failure.

### ISSUE THREAD

**Issue by simekent** [neo4j-contrib/neo4j-spark-connector#579] opened 2023-12-15 03:57 UTC
## Expected Behavior (Mandatory)

When restarting a stream after failure or termination with the same checkpointLocation, the stream should restart from the latest offset.

## Actual Behavior (Mandatory)

The current timestamp (`"streaming.from", "NOW"`) or 0 (`"streaming.from", "ALL"`) is used instead.

## How to Reproduce the Problem

Create a read stream with `"streaming.from", "ALL"`. Start the query, stop the query, then start the query again. The query restarts with offset 0. 

### Simple Dataset (where it's possible)

```
// Insert the output of the `df.show()` call

```

### Steps (Mandatory)

1.
1.
1.

## Specifications (Mandatory)

Currently used versions

### Versions

- Spark: 3.4.0
- Scala: 2.12
- Neo4j: 5.10.0
- Neo4j Connector: 5.2.0

## Additional information

Disclaimer: I am not an expert. If I'm just doing something wrong, please let me know. :)

The neo4j connector appears to be using an Accumulator to store offsets:

https://github.com/neo4j-contrib/neo4j-spark-connector/blob/4071559212bc4a898aa9ca9f5ef8324c328d3293/common/src/main/scala/org/neo4j/spark/streaming/OffsetStorage.scala#L28

Accumulators are not checkpointed so don't survive a restart. This means that on restarting the stream, the initial offset is reported as the latest offset:

https://github.com/neo4j-contrib/neo4j-spark-connector/blob/4071559212bc4a898aa9ca9f5ef8324c328d3293/spark-3/src/main/scala/org/neo4j/spark/streaming/Neo4jMicroBatchReader.scala#L75

Does the offset need to be written to the checkpoint on commit and read on stream restart? I have seen this pattern in other connectors (e.g. https://github.com/mongodb/mongo-spark/blob/main/src/main/java/com/mongodb/spark/sql/connector/read/MongoOffsetStore.java.)

**Comment by conker84** [comment] 2023-12-20 09:32
@simekent thank you so much, could you please provide a simple spark job to replicate the problem?

**Comment by simekent** [comment] 2023-12-27 22:28
Simple pyspark repro is below using a `query` read stream so no data needs to be populated in the database.

Steps to repro for `"streaming,from", "ALL"`:

1. Run `python repro.py -a <dbaddress> -u <username> -p <password> -c /tmp/allcheckpoint -f ALL`

Expected output:
```
RUN 1
-------------------------------------------
Batch: 0
-------------------------------------------
+---------+
|timestamp|
+---------+
|       99|
+---------+
...
-------------------------------------------
Batch: 3
-------------------------------------------
+---------+
|timestamp|
+---------+
|      399|
+---------+
RUN 2
-------------------------------------------
Batch: 4
-------------------------------------------
+---------+
|timestamp|
+---------+
|      499|
+---------+
```

The number of batches might differ depending on your configuration. The important detail is that the single batch from RUN 2 should continue at timestamp + 100 from the previous batch if the offset is read correctly from the checkpoint.

Actual output (Same for RUN 1):
```
RUN 2
-------------------------------------------
Batch: 4
-------------------------------------------
+---------+
|timestamp|
+---------+
|      102|
+---------+
```

Repro for `"timestamp.from", "NOW"` is similar. Run 2 should resume with a timestamp + 100 from the last batch but instead resumes from the latest timestamp. Offsets are written to checkpointLocation but the value is never used when resuming the stream.

repro.py
```
import argparse

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql.streaming.readwriter import DataStreamWriter


def read_stream(
    spark: SparkSession,
    streaming_from: str,
    url: str,
    username: str | None,
    password: str | None,
):
    stream = (
        spark.readStream.format("org.neo4j.spark.DataSource")
        .option("url", url)
        .option("streaming.from", streaming_from)
        .option("streaming.property.name", "timestamp")
        .option("query", "RETURN $stream.offset + 100 AS timestamp")
        .option("streaming.query.offset", "RETURN timestamp() AS timestamp")
    )
    if username:
        stream = stream.option("authentication.basic.username", username)
    if password:
        stream = stream.option("authentication.basic.password", password)

    return stream.load()


def stream_writer(stream_df: DataFrame, checkpoint_location: str):
    return stream_df.writeStream.option(
        "checkpointLocation", checkpoint_location
    ).format("console")


def repro(writer: DataStreamWriter, processing_time: str = "500 milliseconds"):
    print("RUN 1")
    streaming_query = writer.trigger(processingTime=processing_time).start()
    streaming_query.awaitTermination(3)
    streaming_query.stop()

    # Stop the stream and resume for one trigger simulating failure after restart.
    print("RUN 2")
    streaming_query = writer.trigger(once=True).start()
    streaming_query.awaitTermination(3)
    streaming_query.stop()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-a", "--address", type=str, default="bolt://localhost:7687")
    parser.add_argument("-p", "--password", type=str, nargs="?")
    parser.add_argument("-u", "--username", type=str, nargs="?")
    parser.add_argument("-c", "--checkpointLocation", type=str, required=True)
    parser.add_argument(
        "-f", "--streamingFrom", type=str, choices=["NOW", "ALL"], default="ALL"
    )
    args = parser.parse_args()
    spark = (
        SparkSession.Builder()
        .config(
            "spark.jars.packages",
            "org.neo4j:neo4j-connector-apache-spark_2.12:5.2.0_for_spark_3",
        )
        .master("local[*]")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("FATAL")

    stream_df = read_stream(
        spark, args.streamingFrom, args.address, args.username, args.password
    )
    writer = stream_writer(stream_df, args.checkpointLocation)
    repro(writer)
```

**Comment by conker84** [comment] 2024-01-02 09:55
Ok, I see your point. The behaviour in that case is right as the **source** uses the `checkpointLocation` that you highlighted in the [MongoOffsetStorage](https://github.com/mongodb/mongo-spark/blob/main/src/main/java/com/mongodb/spark/sql/connector/read/MongoOffsetStore.java#L48) **only for fault tolerance**. The URL is managed by Spark itself and is not used for starting from the last consumed offset. We could add a feature that allows the users to provide a custom checkpoint location like:

```scala
spark.readStream.format("org.neo4j.spark.DataSource")
        .option("url", url)
        .option("streaming.from", "location")
        .option("streaming.from.location", "/tmp/mydir")
        .option("streaming.property.name", "timestamp")
        .option("query", "RETURN $stream.offset + 100 AS timestamp")
        .option("streaming.query.offset", "RETURN timestamp() AS timestamp")
```

And use it for the offset storage.

/cc @fbiville @ali-ince wdyt about that feature?

**Comment by simekent** [comment] 2024-01-02 19:06
Can you explain this statement in more detail?

> The behaviour in that case is right as the source uses the checkpointLocation that you highlighted in the [MongoOffsetStorage](https://github.com/mongodb/mongo-spark/blob/main/src/main/java/com/mongodb/spark/sql/connector/read/MongoOffsetStore.java#L48) only for fault tolerance. The URL is managed by Spark itself and is not used for starting from the last consumed offset.

The other Spark streaming sources we use (Kafka, delta tables, ...) do restart from the last offset without providing additional configuration apart from the `checkpointLocation`. (If we want to restart, we delete the checkpoints.) The spark doc on [Recovering from Failures with Checkpointing](https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#recovering-from-failures-with-checkpointing) seems to indicate this is expected?

Our scenario requires at-least once stream processing, but too much replay can be problematic. We need to regularly restart streams for maintenance. With `"streaming.from", "ALL"` our entire stream is replayed on every restart. With `"streaming.from", "NOW"` we can lose items in between restarts so the at-least requirement is not satisfied. Our current approach is to go with `ALL` with some error-prone checks and garbage collection. It would be great if the neo4j connector supported restart from checkpoints out of the box.

**Comment by conker84** [comment] 2024-01-03 10:01
This statement is totally **wrong**:

> The other Spark streaming sources we use (Kafka, delta tables, ...) do restart from the last offset without providing additional configuration apart from the `checkpointLocation`.

When you're saying *streaming sources* for Spark you're referring to a spark job that starts with `spark.readStream` and for this kind of jobs there is no `checkpointLocation` option available; that option is available for **sink jobs** so the once that start with `spark.writeStream`

You're complaining about, quoting:

> With "streaming.from", "ALL" our entire stream is replayed on every restart. With "streaming.from", "NOW" we can lose items in between restarts so the at-least requirement is not satisfied

And this will happen, IMHO, also for Mongo and other databases unless they don't track internally the reads; **Kafka source works just fine because its source uses a Kafka Consumer for reading the topics, and it has an internal mechanism to track the last read `offset`.** Delta tables, I'm honest, IDK how they work internally.

As you can see I suggested an option to my colleagues to provide some kind of tracking within the connector; and that's the only way that could, in my knowledge (but I'm open to suggestions), fix your use-case.

So in the end Spark does not provide for **source jobs** any checkpointing feature, Kafka has it because of how it works internally; the docs page that you linked is for **sink jobs**.

I hope that is more clear now. If you have more questions I'm here.

**Comment by simekent** [comment] 2024-01-03 21:06
@conker84 thanks for being patient with me. Like I said earlier, I am not an expert. If I'm just doing something wrong, please let me know. :)

> When you're saying streaming sources for Spark you're referring to a spark job that starts with spark.readStream and for this kind of jobs there is no checkpointLocation option available; that option is available for sink jobs so the once that start with spark.writeStream

Apologies for being imprecise with language here. The option is certainly only available for sink jobs. However, the sink doesn't seem to matter. My repro above has a console sink but we have other jobs that use different sinks. The offsets that are written to the checkpoints are always source offsets. (More on that later.) I hope that clears it up.

> Kafka source works just fine because its source uses a Kafka Consumer for reading the topics, and it has an internal mechanism to track the last read offset.

We do have some experience using the Kafka connector. The Kafka source doesn't commit any offsets to Kafka itself [per this doc](https://spark.apache.org/docs/latest/structured-streaming-kafka-integration.html#kafka-specific-configurations) and [older docs](https://spark.apache.org/docs/latest/streaming-kafka-0-10-integration.html#checkpoints) state that offsets are stored in the checkpoint only unless you commit offsets yourself. We use Kafka for other purposes where we do commit offsets we do see those consumer groups and offsets in Kafka, whereas there are none from our spark jobs.

I [modified my repro](https://github.com/simekent/neo4jspark-579/blob/main/kafka_repro.py) to use a Kafka source to check my assumptions. The repro has an option of deleting individual checkpoints (the files under `commits` and `offsets` directories under the `checkpointLocation`.) If I start the query and it runs for 10 batches, then I delete commits and offsets from 5 on, then the next query will restart at 5. This is consistent with our experience of using checkpoints. The kafka source `startingOffsets` configuration only applies when the query is run the first time when checkpoints are used. 

> Delta tables, I'm honest, IDK how they work internally.

Delta tables are basically just parquet with version control and have more have more complicated offsets as a result. They do behave the same way as the Kafka source with respect to checkpoints. The query always resumes from the last offset written in the checkpointLocation and deleting individual offsets has the same effect. ([Repro for delta tables](https://github.com/simekent/neo4jspark-579/blob/main/delta_repro.py).)

> So in the end Spark does not provide for source jobs any checkpointing feature, Kafka has it because of how it works internally; the docs page that you linked is for sink jobs.

Can you help me understand what you mean by this? If I look into the individual offset files in the checkpointLocation for the console sink in my repro, I can see that spark is writing the serialized source offsets in the last line of the offset files. e.g. 

Neo4j is just a long:
```
~/checkpoints/neo4j $ tail -1 offsets/3
299
```

Kafka has topic, partition, and offset:
```
~/checkpoints/kakfa $ tail -1 offsets/3
{"test-topic":{"0":4}}
```

And Delta:
```
~/checkpoints/delta $ tail -1 offsets/3
{"sourceVersion":1,"reservoirId":"c3a22f1f-3173-415e-9707-962eb318216d","reservoirVersion":0,"index":3,"isStartingVersion":true}
```

Aren't checkpoints are just offsets from the source up to which everything has been successful read from the source and written to the sink?

Another question on the repro: do you know why the existence of the checkpointLocation affects the offset when the stream restarts? i.e. if I start the query with a fresh checkpointLocation, the first batch returns 99, which means the offset is -1. When I restart the query, the first batch returns 102, which means the offset is 2. Restarting again sometimes returns 101 or 102 or 103. Is there something happening on stream start (schema inference?) that might be modifying the offset provided by spark?

**Comment by conker84** [comment] 2024-01-04 10:11
Spark Streaming for Kafka **source** jobs internally uses a Kafka Consumer.

A Kafka Consumer stores the last read record as committed offset. To guarantee that the job recover from the last read offset you specify `.option("kafka.group.id", "mik")` which after a failure (or a manual stop) says "Ok I'm `mik`, I'm back now, please continue to pull the data from the topic from where we're interrupted".

For the checkpoint value Neo4j is just a long correct, each data source can have its implementation, in fact as you can see Kafka and Delta have no fields in common. In the future maybe we could switch to a JSON representation.

**Comment by simekent** [comment] 2024-01-04 18:36
> Spark Streaming for Kafka **source** jobs internally uses a Kafka Consumer.
> 
> A Kafka Consumer stores the last read record as committed offset. To guarantee that the job recover from the last read offset you specify `.option("kafka.group.id", "mik")` which after a failure (or a manual stop) says "Ok I'm `mik`, I'm back now, please continue to pull the data from the topic from where we're interrupted".

That setting is a red herring. I used that setting in the repro so I could check whether offsets were stored for that consumer group. If the setting is removed the behavior is the same. The Kafka spark connector does not use the Consumer to store committed offsets. 

The repro can be used to demonstrate the above in lots of ways. Run the repro once, edit the `kafka.group.id` setting or remove it completely, then run it again, and the query will restart from the offset that the first run of the repro stopped. I can go even further with my setup and run the repro saving only checkpoints to a durable location, tear down and restart the entire cluster, recreate and populate a topic with the same name in the clean kafka instance, then run the repro again in the clean spark cluster. The query always restarts from the last checkpoint in the `checkpointLocation`. Which makes entire sense because the offset stored in the `checkpointLocation` is just an address within the the kafka topic (topic name, partition, offset.)

I can perform a similar repro with Delta tables by the way, modulo the fact that I can't reseed the data. Instead, I can run the repro, take a copy of the table, run the repro on the original, then run the repro on the copy. With all other state removed by restarting the cluster, the stream starts at the "correct" offset when running from the copy, which indicates that the metadata about the state of the query is stored in the `checkpointLocation` rather that somewhere else.

The [spark kafka integration guide](https://spark.apache.org/docs/latest/structured-streaming-kafka-integration.html) has a lot more detail about how consumers are used (or not) including the reasons for (or against) specifying a `kafka.group.id`.
 
> 
> For the checkpoint value Neo4j is just a long correct, each data source can have its implementation, in fact as you can see Kafka and Delta have no fields in common. In the future maybe we could switch to a JSON representation.

Right, the Neo4j representation being a long makes sense at the moment. The interesting point is that the source offsets are stored in checkpoints just by specifying the `checkpointLocation` option on the writer and the kind of sink doesn't matter. In this case I use a console sink but in our production queries we use other sinks. The offsets stored are still source offsets and the behavior is the same as far as restarting the queries goes.

The more I look into this, the more I think that:

1. My initial guess at what a fix might be was naive and not correct, and 
2. There is something going on with the neo4j connector on restarting queries from a checkpoint that prevents the correct offset from being used. The fact that the neo4j query from `ALL` starts at a slightly different offset depending on whether there is a checkpoint or not seems like an interesting starting point.
3. This is a bug because reliably restarting queries is a primary motivation for checkpoints. 

I don't think I can add any more information to motivate a fix here. I look forward to hearing what you and your colleagues suggest. Reliable restarts are a firm requirement for our use cases.

**Comment by ali-ince** [comment] 2024-02-09 13:14
Hello @simekent,

We have followed up internally on this issue and identified a mis-behaviour in our connector for handling offsets during micro batch preparation. We are working on a fix right now, but that will take a bit of time on our side and also will require a deprecation around streaming query option (will need to introduce another parameter).

Thanks for your helpful reproduction and explanation of the problem.

**Comment by simekent** [comment] 2024-02-10 04:09
Thanks @ali-ince and @conker84 for following up. I can see how the change in behavior requires a deprecation. Thoughtful engineering. I look forward to the fix!

**Closed as completed** 2024-09-16 10:21 UTC
Labels: enhancement
