### ISSUE TITLE
Spark job dont stop and too many executors consuming avalaible resources on cloud

### ISSUE THREAD

**Issue by L4R4** [neo4j-contrib/neo4j-spark-connector#272] opened 2021-01-05 19:33 UTC
Enviroment:
Spark 2.4.2 in Stand-Alone Mode (i try in Mesos too)
Scala 2.12.7
Neo4j 3.5.4

When I try a code like the documentation example:

[Main.txt](https://github.com/neo4j-contrib/neo4j-spark-connector/files/5772151/Main.txt)

Using this maven configuration:

[pom.txt](https://github.com/neo4j-contrib/neo4j-spark-connector/files/5772156/pom.txt)

The spark job give me results, it show the DataFrame and print in console (----FINISH-----), but the driver keep alive waiting to be stopped. Also the executors tab in spark web-ui show no active task

**IMPORTANT**:

This issue causes that exists many zombies executors consuming avalaible resources

**Comment by conker84** [comment] 2021-01-09 12:48
@L4R4 I think that the problem is that you're not closing the spark session:

`spark.stop()`

**Comment by conker84** [comment] 2021-01-11 12:49
@L4R4 ping

**Comment by L4R4** [comment] 2021-01-12 13:33
I think it isn't the problem I close both spark session and spark context and still the same problem I think that is when spark submmit master is a cluster, becuase i test in local and the job terminate succesfully

**Comment by conker84** [comment] 2021-01-14 09:56
Sorry I don't understand what you mean, can you elaborate the problem?

**Comment by L4R4** [comment] 2021-01-18 15:57
Thanks for response.

I try this simple example, with the Movie database from Neo4j:

object Main extends App {

  val sc: SparkContext = {
    val conf: SparkConf = new SparkConf()
    new SparkContext(conf)
  }

  val spark = SparkSession.builder.config(sc.getConf).getOrCreate()
  val neo4jUrl = sc.getConf.get("spark.neo4j.url")
  val neo4jUser = sc.getConf.get("spark.neo4j.user")
  val neo4jPass = sc.getConf.get("spark.neo4j.password")

  val graph = spark.read.format(classOf[DataSource].getName).
    option("url", neo4jUrl).
    option("authentication.type", "basic").
    option("schema.strategy", "string").
    option("authentication.basic.username", neo4jUser).
    option("authentication.basic.password", neo4jPass).
    option("query", "MATCH (n: Movie) RETURN id(n) as id, n.title as title").
    load()

  graph.show()

  println("FINISH")
  spark.close()
  sc.stop()
}

I use spark-submmit to run the app in Spark:

spark-submit --name TestGraph\
 --conf spark.neo4j.url=bolt://localhost:7687\
 --conf spark.neo4j.user=neo4j\
 --conf spark.neo4j.password=admin\
 --master local[*]\
 --class cu.me.test.Main\
 spark-test-1.0.jar

With --master set to local[*], the job print "FINISH" and exit successfully. But, whit --master set to a spark cluster, and --deploy-mode option is set to cluster (I try with spark:// and mesos://), the job print FINISH, even the spark session and spark context are stopped, but the job isn't stopped on the cluster.

**Comment by conker84** [comment] 2021-01-22 13:17
Please share the spark job ui status before and after the job

**Comment by moxious** [comment] 2021-03-12 14:19
Closed, because we can't identify next actions here, not enough information to move forward.

**Closed as completed by moxious** 2021-03-12 14:19 UTC
